name: Gradle Package

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build

      - name: Upload build artifacts api
        uses: actions/upload-artifact@v3
        with:
          name: api-build
          path: api/build/libs

      - name: Upload build artifacts spigot
        uses: actions/upload-artifact@v3
        with:
          name: spigot-build
          path: spigot/build/libs

      - name: Upload build artifacts netty-common
        uses: actions/upload-artifact@v3
        with:
          name: netty-common-build
          path: netty-common/build/libs

      - name: Upload build artifacts bungeecord
        uses: actions/upload-artifact@v3
        with:
          name: bungeecord-build
          path: bungeecord/build/libs

      - name: Upload build artifacts velocity
        uses: actions/upload-artifact@v3
        with:
          name: velocity-build
          path: velocity/build/libs

      - name: Upload build artifacts fabric
        uses: actions/upload-artifact@v3
        with:
          name: fabric-build
          path: fabric/build/libs